@Host = http://localhost:3002

### Category
### GET ALL CATEGORIES
GET {{Host}}/category HTTP/1.1
### GET CATEGORY BY ID
GET {{Host}}/category/6358a8a8d67246536825ca91 HTTP/1.1
### CREATE NEW CATEGORY
POST {{Host}}/category HTTP/1.1
content-type: application/json

{
    "name": "category test 1"
}
### UPDATE CATEGORY
PUT {{Host}}/category/635c92f641b4994d3fbe77f9 HTTP/1.1
content-type: application/json

{
    "name": "category update 2",
}
### DELETE CATEGORY
DELETE {{Host}}/category/635c92f641b4994d3fbe77f9 HTTP/1.1
###
### Risk Level
### GET ALL
GET {{Host}}/risk-level HTTP/1.1
### GET BY ID
GET {{Host}}/risk-level/635d9d9e93b2bfccf5164bfc HTTP/1.1
### CREATE 
POST {{Host}}/risk-level HTTP/1.1
content-type: application/json

{
    "name": "risk level test 3"
}
### UPDATE
PUT {{Host}}/risk-level/635d9d9e93b2bfccf5164bfc HTTP/1.1
content-type: application/json

{
    "name": "risk level update 2"
}
### DELETE
DELETE {{Host}}/risk-level/635d9dbd93b2bfccf5164bfd HTTP/1.1
###
### Consume Frequency
### GET ALL
GET {{Host}}/consume-frequency HTTP/1.1
### GET BY ID
GET {{Host}}/consume-frequency/635de6e68e238e5869b21651 HTTP/1.1
### CREATE 
POST {{Host}}/consume-frequency HTTP/1.1
content-type: application/json

{
    "frequency": "5 per day"
}
### UPDATE
PUT {{Host}}/consume-frequency/635de6ee8e238e5869b21652 HTTP/1.1
content-type: application/json

{
    "frequency": "Moderation"
}
### DELETE
DELETE {{Host}}/consume-frequency/635de6e68e238e5869b21651 HTTP/1.1
###
### Severity Scale
### GET ALL SEVERITIES
GET {{Host}}/severity-scale HTTP/1.1
### GET SEVERITY BY ID
GET {{Host}}/severity-scale/636172586a00904c6b70ba20 HTTP/1.1
### CREATE NEW SEVERITY
POST {{Host}}/severity-scale HTTP/1.1
content-type: application/json

{
    "name": "severity scale 1",
    "description": "i am a severity",
    "icon": "pretty-icon"
}
### UPDATE SEVERITY
PUT {{Host}}/severity-scale/636172586a00904c6b70ba20 HTTP/1.1
content-type: application/json

{
    "name": "update severity scale 2",
    "description": "i am a severity",
    "icon": "pretty-icon"
}
### DELETE SEVERITY
DELETE {{Host}}/severity-scale/636172586a00904c6b70ba20 HTTP/1.1
###
### Symptom
### GET ALL SYMPTOMS
GET {{Host}}/symptom HTTP/1.1
### GET SYMPTOM BY ID
GET {{Host}}/symptom/63afa7af42be90e3a4e1be08 HTTP/1.1
### CREATE NEW SYMPTOM
POST {{Host}}/symptom HTTP/1.1
content-type: application/json

{
    "name": "symptom 2",
    "severityScaleId": "63618a047438717bc9f1f1e3"
}
### UPDATE SYMPTOM
PUT {{Host}}/symptom/ID HTTP/1.1
content-type: application/json

{
    "name": "update symptom 2",
    "severityScaleId": "63618a027438717bc9f1f1e0"
}
### DELETE SYMPTOM
DELETE {{Host}}/symptom/636f06c1c822c8919d3d203a HTTP/1.1
###
### Symptom
### GET ALL FOODS
GET {{Host}}/food HTTP/1.1
### GET FOOD BY ID
GET {{Host}}/food/63afa86342be90e3a4e1be09 HTTP/1.1
### CREATE NEW FOOD
POST {{Host}}/food HTTP/1.1
content-type: application/json

{
    "name": "Completo 2",
    "description": "Bien grande como te gusta",
    "suggestions": ["Cierra los ojos y pa entro"],
    "symptomsIds": ["63afa7af42be90e3a4e1be08"],
    "categoryId": "6358a8a7d67246536825ca90",
    "riskLevelId": "635d9d9a93b2bfccf5164bfb",
    "consumeFrequencyId": "635de6ee8e238e5869b21652",
    "isEdible": "YES"
}
### UPDATE FOOD
PUT {{Host}}/food/63afa86342be90e3a4e1be09 HTTP/1.1
content-type: application/json

{
    "name": "Chorrillana"
}
### DELETE FOOD
DELETE {{Host}}/food/63afa86342be90e3a4e1be09 HTTP/1.1